CREATE DATABASE IF NOT EXISTS honestbee_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE honestbee_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS substitution;
DROP TABLE IF EXISTS refund;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS payment_transaction;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customer_order;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS rider;
DROP TABLE IF EXISTS merchant;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS id_sequence;
DROP TABLE IF EXISTS service_city;
DROP TABLE IF EXISTS admin;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS admin (
  ADMIN_id VARCHAR(120) NOT NULL PRIMARY KEY,
  ADMIN_email VARCHAR(190) NOT NULL UNIQUE,
  ADMIN_password VARCHAR(255) NOT NULL,
  ADMIN_fullName VARCHAR(190) DEFAULT NULL,
  ADMIN_status VARCHAR(40) NOT NULL DEFAULT 'Active',
  ADMIN_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_city (
  CITY_name VARCHAR(80) NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS id_sequence (
  SEQ_key VARCHAR(40) NOT NULL PRIMARY KEY,
  SEQ_prefix VARCHAR(8) NOT NULL,
  SEQ_next INT NOT NULL DEFAULT 1,
  SEQ_updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO service_city (CITY_name) VALUES
  ('Cebu City'),
  ('Lapu-Lapu'),
  ('Mandaue'),
  ('Consolacion'),
  ('Talisay')
ON DUPLICATE KEY UPDATE
  CITY_name = VALUES(CITY_name);

INSERT INTO id_sequence (SEQ_key, SEQ_prefix, SEQ_next) VALUES
  ('customer', 'C', 1),
  ('merchant', 'M', 1),
  ('rider', 'R', 1)
ON DUPLICATE KEY UPDATE
  SEQ_prefix = VALUES(SEQ_prefix);

CREATE TABLE IF NOT EXISTS customer (
  CUST_id VARCHAR(120) NOT NULL PRIMARY KEY,
  CUST_firstName VARCHAR(80) DEFAULT NULL,
  CUST_lastName VARCHAR(80) DEFAULT NULL,
  CUST_email VARCHAR(190) DEFAULT NULL,
  CUST_password VARCHAR(255) DEFAULT NULL,
  CUST_role VARCHAR(40) NOT NULL DEFAULT 'customer',
  CUST_status VARCHAR(40) NOT NULL DEFAULT 'Active',
  CUST_phone VARCHAR(20) DEFAULT NULL,
  CUST_city VARCHAR(80) DEFAULT NULL,
  CUST_address TEXT DEFAULT NULL,
  CUST_preferredDeliveryTime VARCHAR(60) DEFAULT NULL,
  CUST_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CUST_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_customer_email (CUST_email),
  INDEX idx_customer_status (CUST_status),
  INDEX idx_customer_city (CUST_city),
  CONSTRAINT fk_customer_city FOREIGN KEY (CUST_city) REFERENCES service_city (CITY_name)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant (
  MERCH_id VARCHAR(120) NOT NULL PRIMARY KEY,
  MERCH_ownerFirstName VARCHAR(80) DEFAULT NULL,
  MERCH_ownerLastName VARCHAR(80) DEFAULT NULL,
  MERCH_ownerEmail VARCHAR(190) DEFAULT NULL,
  MERCH_password VARCHAR(255) DEFAULT NULL,
  MERCH_phone VARCHAR(20) DEFAULT NULL,
  MERCH_name VARCHAR(190) DEFAULT NULL,
  MERCH_type VARCHAR(80) DEFAULT NULL,
  MERCH_address TEXT DEFAULT NULL,
  MERCH_businessHours VARCHAR(120) DEFAULT NULL,
  MERCH_businessProof TEXT DEFAULT NULL,
  MERCH_availableDays VARCHAR(190) DEFAULT NULL,
  MERCH_preparationTime VARCHAR(80) DEFAULT NULL,
  MERCH_storeStatus VARCHAR(40) NOT NULL DEFAULT 'Open',
  MERCH_approvalStatus VARCHAR(40) NOT NULL DEFAULT 'Pending',
  MERCH_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MERCH_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_merchant_email (MERCH_ownerEmail),
  INDEX idx_merchant_status (MERCH_approvalStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rider (
  RIDER_id VARCHAR(120) NOT NULL PRIMARY KEY,
  RIDER_firstName VARCHAR(80) DEFAULT NULL,
  RIDER_lastName VARCHAR(80) DEFAULT NULL,
  RIDER_email VARCHAR(190) DEFAULT NULL,
  RIDER_password VARCHAR(255) DEFAULT NULL,
  RIDER_phone VARCHAR(20) DEFAULT NULL,
  RIDER_currentLocation VARCHAR(190) DEFAULT NULL,
  RIDER_vehicleType VARCHAR(80) DEFAULT NULL,
  RIDER_validId TEXT DEFAULT NULL,
  RIDER_availabilityStatus VARCHAR(40) NOT NULL DEFAULT 'Unavailable',
  RIDER_employmentStatus VARCHAR(40) NOT NULL DEFAULT 'Pending',
  RIDER_maxActiveOrders INT NOT NULL DEFAULT 1,
  RIDER_role VARCHAR(40) NOT NULL DEFAULT 'rider',
  RIDER_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RIDER_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_rider_email (RIDER_email),
  INDEX idx_rider_status (RIDER_employmentStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  PROD_id VARCHAR(120) NOT NULL PRIMARY KEY,
  PROD_merchantId VARCHAR(120) DEFAULT NULL,
  PROD_merchantName VARCHAR(190) DEFAULT NULL,
  PROD_name VARCHAR(190) DEFAULT NULL,
  PROD_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  PROD_category VARCHAR(120) DEFAULT NULL,
  PROD_unit VARCHAR(80) DEFAULT NULL,
  PROD_description TEXT DEFAULT NULL,
  PROD_type VARCHAR(40) DEFAULT NULL,
  PROD_tag VARCHAR(80) DEFAULT NULL,
  PROD_rating VARCHAR(20) DEFAULT NULL,
  PROD_image TEXT DEFAULT NULL,
  PROD_alt VARCHAR(190) DEFAULT NULL,
  PROD_approvalStatus VARCHAR(40) NOT NULL DEFAULT 'Active',
  PROD_source VARCHAR(80) DEFAULT NULL,
  PROD_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PROD_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_product_merchant (PROD_merchantId),
  INDEX idx_product_status (PROD_approvalStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivery (
  DEL_id VARCHAR(120) NOT NULL PRIMARY KEY,
  DEL_orderId VARCHAR(120) DEFAULT NULL,
  DEL_address TEXT DEFAULT NULL,
  DEL_serviceArea VARCHAR(190) DEFAULT NULL,
  DEL_status VARCHAR(60) NOT NULL DEFAULT 'Pending',
  DEL_time VARCHAR(120) DEFAULT NULL,
  DEL_serviceHours VARCHAR(120) DEFAULT NULL,
  DEL_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DEL_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_delivery_status (DEL_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_order (
  ORDER_id VARCHAR(120) NOT NULL PRIMARY KEY,
  ORDER_customerId VARCHAR(120) DEFAULT NULL,
  ORDER_riderId VARCHAR(120) DEFAULT NULL,
  ORDER_merchantId VARCHAR(120) DEFAULT NULL,
  ORDER_deliveryId VARCHAR(120) DEFAULT NULL,
  ORDER_status VARCHAR(60) NOT NULL DEFAULT 'Placed',
  ORDER_totalAmount DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_scheduledTime VARCHAR(120) DEFAULT NULL,
  ORDER_paymentMethod VARCHAR(80) DEFAULT NULL,
  ORDER_paymentStatus VARCHAR(80) DEFAULT NULL,
  ORDER_paymentReference VARCHAR(120) DEFAULT NULL,
  ORDER_paymentProof TEXT DEFAULT NULL,
  ORDER_customerEmail VARCHAR(190) DEFAULT NULL,
  ORDER_customerName VARCHAR(190) DEFAULT NULL,
  ORDER_customerPhone VARCHAR(20) DEFAULT NULL,
  ORDER_customerAddress TEXT DEFAULT NULL,
  ORDER_merchantName VARCHAR(190) DEFAULT NULL,
  ORDER_cardLast4 VARCHAR(4) DEFAULT NULL,
  ORDER_cardholderName VARCHAR(190) DEFAULT NULL,
  ORDER_storeSource VARCHAR(80) DEFAULT NULL,
  ORDER_storeStatus VARCHAR(80) DEFAULT NULL,
  ORDER_needsSellerPayCheck TINYINT(1) NOT NULL DEFAULT 0,
  ORDER_sellerPaymentVerified TINYINT(1) NOT NULL DEFAULT 0,
  ORDER_paymentVerification VARCHAR(120) DEFAULT NULL,
  ORDER_paymentVerifiedBy VARCHAR(120) DEFAULT NULL,
  ORDER_paymentVerifiedAt DATETIME DEFAULT NULL,
  ORDER_rejectedRiders TEXT DEFAULT NULL,
  ORDER_lastRiderId VARCHAR(120) DEFAULT NULL,
  ORDER_lastRiderAction VARCHAR(60) DEFAULT NULL,
  ORDER_subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_deliveryFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_serviceFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_itemCount INT NOT NULL DEFAULT 0,
  ORDER_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ORDER_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_customer_order_customer (ORDER_customerId),
  INDEX idx_customer_order_merchant (ORDER_merchantId),
  INDEX idx_customer_order_rider (ORDER_riderId),
  INDEX idx_customer_order_status (ORDER_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  ORDER_id VARCHAR(120) NOT NULL PRIMARY KEY,
  ORDER_customerId VARCHAR(120) DEFAULT NULL,
  ORDER_riderId VARCHAR(120) DEFAULT NULL,
  ORDER_merchantId VARCHAR(120) DEFAULT NULL,
  ORDER_deliveryId VARCHAR(120) DEFAULT NULL,
  ORDER_status VARCHAR(60) NOT NULL DEFAULT 'Placed',
  ORDER_totalAmount DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_scheduledTime VARCHAR(120) DEFAULT NULL,
  ORDER_paymentMethod VARCHAR(80) DEFAULT NULL,
  ORDER_paymentStatus VARCHAR(80) DEFAULT NULL,
  ORDER_paymentReference VARCHAR(120) DEFAULT NULL,
  ORDER_paymentProof TEXT DEFAULT NULL,
  ORDER_customerEmail VARCHAR(190) DEFAULT NULL,
  ORDER_customerName VARCHAR(190) DEFAULT NULL,
  ORDER_customerPhone VARCHAR(20) DEFAULT NULL,
  ORDER_customerAddress TEXT DEFAULT NULL,
  ORDER_merchantName VARCHAR(190) DEFAULT NULL,
  ORDER_cardLast4 VARCHAR(4) DEFAULT NULL,
  ORDER_cardholderName VARCHAR(190) DEFAULT NULL,
  ORDER_storeSource VARCHAR(80) DEFAULT NULL,
  ORDER_storeStatus VARCHAR(80) DEFAULT NULL,
  ORDER_needsSellerPayCheck TINYINT(1) NOT NULL DEFAULT 0,
  ORDER_sellerPaymentVerified TINYINT(1) NOT NULL DEFAULT 0,
  ORDER_paymentVerification VARCHAR(120) DEFAULT NULL,
  ORDER_paymentVerifiedBy VARCHAR(120) DEFAULT NULL,
  ORDER_paymentVerifiedAt DATETIME DEFAULT NULL,
  ORDER_rejectedRiders TEXT DEFAULT NULL,
  ORDER_lastRiderId VARCHAR(120) DEFAULT NULL,
  ORDER_lastRiderAction VARCHAR(60) DEFAULT NULL,
  ORDER_subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_deliveryFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_serviceFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  ORDER_itemCount INT NOT NULL DEFAULT 0,
  ORDER_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ORDER_updatedAt DATETIME DEFAULT NULL,
  INDEX idx_orders_status (ORDER_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_item (
  ITEM_id VARCHAR(120) NOT NULL PRIMARY KEY,
  ITEM_orderId VARCHAR(120) DEFAULT NULL,
  ITEM_productId VARCHAR(120) DEFAULT NULL,
  ITEM_merchantId VARCHAR(120) DEFAULT NULL,
  ITEM_merchantName VARCHAR(190) DEFAULT NULL,
  ITEM_name VARCHAR(190) DEFAULT NULL,
  ITEM_quantity INT NOT NULL DEFAULT 1,
  ITEM_unitPrice DECIMAL(10,2) NOT NULL DEFAULT 0,
  ITEM_unit VARCHAR(80) DEFAULT NULL,
  ITEM_image TEXT DEFAULT NULL,
  ITEM_instructions TEXT DEFAULT NULL,
  ITEM_substitutePolicy VARCHAR(40) DEFAULT NULL,
  ITEM_substituteName VARCHAR(190) DEFAULT NULL,
  ITEM_status VARCHAR(60) NOT NULL DEFAULT 'Available',
  ITEM_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_order_item_order (ITEM_orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_transaction (
  PAY_id VARCHAR(120) NOT NULL PRIMARY KEY,
  PAY_orderId VARCHAR(120) DEFAULT NULL,
  PAY_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  PAY_method VARCHAR(80) DEFAULT NULL,
  PAY_status VARCHAR(60) NOT NULL DEFAULT 'Authorized',
  PAY_reference VARCHAR(120) DEFAULT NULL,
  PAY_proof TEXT DEFAULT NULL,
  PAY_cardLast4 VARCHAR(4) DEFAULT NULL,
  PAY_cardholderName VARCHAR(190) DEFAULT NULL,
  PAY_verificationStatus VARCHAR(120) DEFAULT NULL,
  PAY_verifiedBy VARCHAR(120) DEFAULT NULL,
  PAY_verifiedAt DATETIME DEFAULT NULL,
  PAY_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_payment_order (PAY_orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rating (
  RATE_id VARCHAR(120) NOT NULL PRIMARY KEY,
  RATE_orderId VARCHAR(120) DEFAULT NULL,
  RATE_customerId VARCHAR(120) DEFAULT NULL,
  RATE_riderId VARCHAR(120) DEFAULT NULL,
  RATE_serviceScore INT NOT NULL DEFAULT 5,
  RATE_shopperScore INT NOT NULL DEFAULT 5,
  RATE_feedbackComment TEXT DEFAULT NULL,
  RATE_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rating_order (RATE_orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refund (
  REFUND_id VARCHAR(120) NOT NULL PRIMARY KEY,
  REFUND_orderId VARCHAR(120) DEFAULT NULL,
  REFUND_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  REFUND_reason TEXT DEFAULT NULL,
  REFUND_status VARCHAR(60) NOT NULL DEFAULT 'Pending',
  REFUND_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_refund_order (REFUND_orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS substitution (
  SUB_id VARCHAR(120) NOT NULL PRIMARY KEY,
  SUB_itemId VARCHAR(120) DEFAULT NULL,
  SUB_orderId VARCHAR(120) DEFAULT NULL,
  SUB_originalItem VARCHAR(190) DEFAULT NULL,
  SUB_substituteItem VARCHAR(190) DEFAULT NULL,
  SUB_approvalStatus VARCHAR(60) NOT NULL DEFAULT 'Pending',
  SUB_approvalDate DATETIME DEFAULT NULL,
  SUB_createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_sub_order (SUB_orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stores (
  STORE_id VARCHAR(120) NOT NULL PRIMARY KEY,
  STORE_merchantId VARCHAR(120) DEFAULT NULL,
  STORE_status VARCHAR(60) NOT NULL DEFAULT 'Open',
  STORE_reviewedAt DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO admin (
  ADMIN_id,
  ADMIN_email,
  ADMIN_password,
  ADMIN_fullName,
  ADMIN_status
) VALUES (
  'admin-honestbee-dm',
  'admindm@honestbee.com',
  'admin123',
  'Admin',
  'Active'
) ON DUPLICATE KEY UPDATE
  ADMIN_email = VALUES(ADMIN_email),
  ADMIN_status = VALUES(ADMIN_status);
