ALTER TABLE customer_order
  ADD COLUMN IF NOT EXISTS ORDER_paymentReference VARCHAR(120) DEFAULT NULL AFTER ORDER_paymentStatus,
  ADD COLUMN IF NOT EXISTS ORDER_paymentProof TEXT DEFAULT NULL AFTER ORDER_paymentReference;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS ORDER_paymentReference VARCHAR(120) DEFAULT NULL AFTER ORDER_paymentStatus,
  ADD COLUMN IF NOT EXISTS ORDER_paymentProof TEXT DEFAULT NULL AFTER ORDER_paymentReference;

ALTER TABLE payment_transaction
  ADD COLUMN IF NOT EXISTS PAY_proof TEXT DEFAULT NULL AFTER PAY_reference;
